version: "3.9"

services:
  node-backend:
    build: ./backend/node
    ports:
      - "4000:4000"
    depends_on:
      - python-backend

  python-backend:
    build: ./backend/python
    ports:
      - "8000:8000"
